language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.4
    - g++-5.4

env:
  - TRAVIS=travis CXX=g++-4.8

before_script:
  - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx
  - npm install -g mocha
  - npm install -g node-gyp

script:
  - npm test
